# Generated by Django 2.2.7 on 2019-12-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.TextField(blank=True)),
                ('author_name', models.TextField(blank=True)),
                ('reference_number', models.TextField(blank=True)),
                ('book_type', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.TextField(blank=True)),
                ('tieup_with', models.TextField(blank=True)),
            ],
        ),
    ]
