# Generated by Django 2.2.7 on 2020-02-29 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20191214_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email_id',
            field=models.EmailField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
