# Generated by Django 2.2.7 on 2020-02-29 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_login_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
